// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ice_cream_world_backend.models;

#nullable disable

namespace ice_cream_world_backend.Migrations
{
    [DbContext(typeof(IceCreamWorldContext))]
    partial class IceCreamWorldContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ice_cream_world_backend.models.Flavor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<Guid?>("ServingContainerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServingContainerId");

                    b.ToTable("Flavors");
                });

            modelBuilder.Entity("ice_cream_world_backend.models.ServingContainer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .HasColumnType("text");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ServingContainers");
                });

            modelBuilder.Entity("ice_cream_world_backend.models.Flavor", b =>
                {
                    b.HasOne("ice_cream_world_backend.models.ServingContainer", null)
                        .WithMany("Flavors")
                        .HasForeignKey("ServingContainerId");
                });

            modelBuilder.Entity("ice_cream_world_backend.models.ServingContainer", b =>
                {
                    b.Navigation("Flavors");
                });
#pragma warning restore 612, 618
        }
    }
}
